server:
  port: ${PORT:8082}

spring:
  jpa:
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:h2:./ct
    username: sa
    password: passwd
    h2:
      console:
        enabled: true
        path: /h2-console

