# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Develop CI - build 

on:
  push:
    branches:
    - 'develop'
    - 'develop/**'
    - 'feature/**'
    - 'bugfix/**'
    - 'hotfix/**'
    - 'fixes/**'
    - 'release/**'
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file contacts/pom.xml
  
